language: python
python:
  - "2.7"
# command to install dependencies

install:
  - pip install -r requirements.txt

before_script:
  - sed -i 's/API_TOKEN/'"$API_TOKEN"'/g' config.yml

script:
  - behave -f allure_behave.formatter:AllureFormatter -o allure_result_folder

branches:
  only:
    - develop