language: python
python:
  - "2.7"
# command to install dependencies
before_script:
  - pip install -r requirements.txt

script:
  - behave -f allure_behave.formatter:AllureFormatter -o allure_result_folder

branches:
  only:
    - develop